name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: build/test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: install deps
        run: |
          sudo apt update
          sudo apt install -y libudev-dev
      - name: cargo build
        run: cargo build --all-targets
      - name: cargo test
        run: cargo test --all-targets
